nohup: ignoring input
Seed set to 69
wandb: Currently logged in as: philscho (philscho-org). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.17.4 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.16.6
wandb: Run data is saved locally in ./wandb/run-20240711_111807-cbdkw7cd
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run lr=1.5e-04;bs=768
wandb: ‚≠êÔ∏è View project at https://wandb.ai/philscho-org/multimodal
wandb: üöÄ View run at https://wandb.ai/philscho-org/multimodal/runs/cbdkw7cd
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[rank: 0] Seed set to 69
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
[rank: 1] Seed set to 69
[rank: 3] Seed set to 69
[rank: 2] Seed set to 69
[rank: 1] Seed set to 69
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
[rank: 3] Seed set to 69
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
[rank: 2] Seed set to 69
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
[E socket.cpp:860] [c10d] The client socket has timed out after 1800s while trying to connect to (127.0.0.1, 48659).
[E socket.cpp:860] [c10d] The client socket has timed out after 1800s while trying to connect to (127.0.0.1, 48659).
Traceback (most recent call last):
  File "/home/phisch/multimodal/train_model_coco_dualenc_new.py", line 562, in <module>
    main(config)
  File "/home/phisch/multimodal/train_model_coco_dualenc_new.py", line 535, in main
    trainer.fit(net, train_dataloaders=train_dataloader, val_dataloaders=val_dataloaders, ckpt_path=checkpoint)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 543, in fit
    call._call_and_handle_interrupt(
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 942, in _run
    self.strategy.setup_environment()
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/pytorch/strategies/ddp.py", line 154, in setup_environment
    self.setup_distributed()
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/pytorch/strategies/ddp.py", line 203, in setup_distributed
    _init_dist_connection(self.cluster_environment, self._process_group_backend, timeout=self._timeout)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/fabric/utilities/distributed.py", line 291, in _init_dist_connection
    torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 900, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 245, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 176, in _create_c10d_store
    return TCPStore(
TimeoutError: The client socket has timed out after 1800s while trying to connect to (127.0.0.1, 48659).
Traceback (most recent call last):
  File "/home/phisch/multimodal/train_model_coco_dualenc_new.py", line 562, in <module>
    main(config)
  File "/home/phisch/multimodal/train_model_coco_dualenc_new.py", line 535, in main
    trainer.fit(net, train_dataloaders=train_dataloader, val_dataloaders=val_dataloaders, ckpt_path=checkpoint)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 543, in fit
    call._call_and_handle_interrupt(
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 942, in _run
    self.strategy.setup_environment()
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/pytorch/strategies/ddp.py", line 154, in setup_environment
    self.setup_distributed()
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/pytorch/strategies/ddp.py", line 203, in setup_distributed
    _init_dist_connection(self.cluster_environment, self._process_group_backend, timeout=self._timeout)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/fabric/utilities/distributed.py", line 291, in _init_dist_connection
    torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 900, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 245, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 176, in _create_c10d_store
    return TCPStore(
TimeoutError: The client socket has timed out after 1800s while trying to connect to (127.0.0.1, 48659).
[E socket.cpp:860] [c10d] The client socket has timed out after 1800s while trying to connect to (127.0.0.1, 48659).
Traceback (most recent call last):
  File "/home/phisch/multimodal/train_model_coco_dualenc_new.py", line 562, in <module>
    main(config)
  File "/home/phisch/multimodal/train_model_coco_dualenc_new.py", line 535, in main
    trainer.fit(net, train_dataloaders=train_dataloader, val_dataloaders=val_dataloaders, ckpt_path=checkpoint)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 543, in fit
    call._call_and_handle_interrupt(
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 942, in _run
    self.strategy.setup_environment()
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/pytorch/strategies/ddp.py", line 154, in setup_environment
    self.setup_distributed()
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/pytorch/strategies/ddp.py", line 203, in setup_distributed
    _init_dist_connection(self.cluster_environment, self._process_group_backend, timeout=self._timeout)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/lightning/fabric/utilities/distributed.py", line 291, in _init_dist_connection
    torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 900, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 245, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "/home/phisch/venv_py3.8/py3.8/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 176, in _create_c10d_store
    return TCPStore(
TimeoutError: The client socket has timed out after 1800s while trying to connect to (127.0.0.1, 48659).
